"""
FAISS Index Manager

Builds, saves, loads and searches a FAISS index generated
from the embedding pipeline.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

import faiss
import numpy as np

from ..embeddings.config import (
    OUTPUT_EMBEDDINGS_FILE,
    INDEX_FILE,
)
from ..embeddings.models.embedding_result import EmbeddingResult


class FaissManager:
    """
    Manages a FAISS vector index.

    Cosine similarity is implemented by L2-normalizing vectors
    and using IndexFlatIP.
    """

    def __init__(self) -> None:
        self.index: faiss.Index | None = None
        self.ticket_ids: List[str] = []

    def _load_embedding_results(
        self,
        embedding_file: Path = OUTPUT_EMBEDDINGS_FILE,
    ) -> List[EmbeddingResult]:
        """
        Load embeddings generated by the embedding pipeline.
        """

        with embedding_file.open("r", encoding="utf-8") as file:
            raw = json.load(file)

        return [
            EmbeddingResult(
                ticket_id=item["ticket_id"],
                embedding=item["embedding"],
            )
            for item in raw
        ]

    def build(
        self,
        embedding_file: Path = OUTPUT_EMBEDDINGS_FILE,
    ) -> None:
        """
        Build a FAISS index from stored embeddings.
        """

        results = self._load_embedding_results(embedding_file)

        if not results:
            raise ValueError("No embeddings found.")

        self.ticket_ids = [r.ticket_id for r in results]

        vectors = np.asarray(
            [r.embedding for r in results],
            dtype=np.float32,
        )

        faiss.normalize_L2(vectors)

        dimension = vectors.shape[1]

        self.index = faiss.IndexFlatIP(dimension)
        self.index.add(vectors)

    def save(
        self,
        index_file: Path = INDEX_FILE,
    ) -> None:
        """
        Save the FAISS index to disk.
        """

        if self.index is None:
            raise RuntimeError("No FAISS index available to save.")

        faiss.write_index(self.index, str(index_file))

    def load(
        self,
        index_file: Path = INDEX_FILE,
    ) -> None:
        """
        Load a previously saved FAISS index.
        """

        if not index_file.exists():
            raise FileNotFoundError(
                f"FAISS index not found: {index_file}"
            )

        self.index = faiss.read_index(str(index_file))

    def add(
        self,
        embedding: EmbeddingResult,
    ) -> None:
        """
        Add a single embedding to the index.
        """

        if self.index is None:
            raise RuntimeError("FAISS index has not been built.")

        vector = np.asarray(
            [embedding.embedding],
            dtype=np.float32,
        )

        faiss.normalize_L2(vector)

        self.index.add(vector)
        self.ticket_ids.append(embedding.ticket_id)

    def search(
        self,
        query_embedding: List[float],
        top_k: int = 5,
    ) -> List[dict]:
        """
        Search Top-K similar tickets.
        """

        if self.index is None:
            raise RuntimeError("FAISS index has not been built.")

        query = np.asarray(
            [query_embedding],
            dtype=np.float32,
        )

        faiss.normalize_L2(query)

        scores, indices = self.index.search(query, top_k)

        results = []

        for score, index in zip(scores[0], indices[0]):
            if index == -1:
                continue

            results.append(
                {
                    "ticket_id": self.ticket_ids[index],
                    "score": float(score),
                }
            )

        return results

    def is_loaded(self) -> bool:
        """
        Check whether a FAISS index is loaded.
        """

        return self.index is not None