"""
Rebuild Index

Creates a fresh FAISS index using the embeddings
generated by the embedding pipeline.
"""

from __future__ import annotations

from pathlib import Path

from ..embeddings.config import OUTPUT_EMBEDDINGS_FILE
from .faiss_manager import FaissManager


def rebuild_index(
    embedding_file: Path = OUTPUT_EMBEDDINGS_FILE,
) -> FaissManager:
    """
    Rebuild the FAISS index from stored embeddings.

    Args:
        embedding_file:
            Path to embeddings.json.

    Returns:
        A FaissManager with a fully built index.
    """

    manager = FaissManager()
    manager.build(embedding_file)
    manager.save()

    return manager